package io.local.questwebcinema;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.net.http.SslError;
import android.os.Message;
import android.util.Log;
import android.view.*;
import android.view.inputmethod.*;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.regex.*;

/** Desktop-inspired icon chrome, shared by the window and the spatial display. */
public final class CinemaBrowserView extends FrameLayout implements CinemaIcon.HintHost {
    public interface Host { void mode(String mode); void adjust(String action); int curvature(); void curvature(int value); boolean recenterIfNeeded(); boolean movingWindow(); void cursorVisible(boolean visible); void exit(); }
    private final Host host;
    private final boolean immersive;
    private final SharedPreferences prefs;
    private final LinearLayout sidebar,header,compact,content,loading;
    private final FrameLayout stage;
    private final EditText address;
    private final TextView status,tooltip;
    private TextView geometryLabel,curveValue;
    private SeekBar curvatureControl;
    private final ProgressBar progress;
    private final List<CinemaIcon> icons=new ArrayList<>();
    private final Set<WebView> popups=new HashSet<>();
    private final List<JSONObject> sidebarItems=new ArrayList<>();
    private LinearLayout sideNav,tabsRow;
    private View tabStrip;
    private static final class BrowserTab { WebView view; String url,title="新标签页"; BrowserTab(String url){this.url=url;} }
    private final List<BrowserTab> tabs=new ArrayList<>();
    private BrowserTab activeTab;
    private WebView web;
    private String mobileAgent,pendingUrl,modeText="";
    private View fullscreenView,overlay;
    private WebChromeClient.CustomViewCallback fullscreenCallback;
    private boolean focus,disposed,paused,starting,diagnostic,dark;
    private int bg,railColor,text,muted,field;
    private final int pink=0xFF4AA3FF;
    private final Runnable loadTimeout=this::loadingSlow;
    private String layoutScript;
    private int pageGeneration;
    private boolean pageFinished,pagePublished,pageError,pointerVisible,pointerPressed;
    private float pointerX,pointerY,activityPointerX,activityPointerY;
    private long pointerActivity=android.os.SystemClock.uptimeMillis();
    private boolean videoPlaying;
    private final Runnable playerPoll=this::pollPlayer;
    private void pollPlayer(){if(disposed||paused)return;final WebView owner=web;if(owner!=null)owner.evaluateJavascript("Boolean(window.__questBrowser&&window.__questBrowser.playing())",value->{if(disposed||owner!=web)return;videoPlaying="true".equals(value);updatePointerVisibility();});postDelayed(playerPoll,700);}
    private void updatePointerVisibility(){boolean hidden=immersive&&videoPlaying&&overlay==null&&!pointerPressed&&android.os.SystemClock.uptimeMillis()-pointerActivity>2500;if(hidden)pointerVisible=false;host.cursorVisible(!hidden);invalidate();}

    private final Paint pointerPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final Runnable pageMonitor=this::monitorPage;
    private String lastNotice="";
    private long lastNoticeAt;
    private final Runnable hideNotice=this::hideStatus;
    private void hideStatus(){status.setVisibility(GONE);}

    public CinemaBrowserView(Context context,Host host,boolean immersive,String initialUrl){
        super(context);this.host=host;this.immersive=immersive;
        prefs=context.getSharedPreferences("settings",Context.MODE_PRIVATE);
        dark=prefs.getBoolean("dark",immersive);palette();pendingUrl=Navigation.isWeb(initialUrl)?initialUrl:Navigation.HOME;setBackgroundColor(bg);
        LinearLayout shell=row();addView(shell,new FrameLayout.LayoutParams(-1,-1));
        sidebar=column();sidebar.setPadding(dp(10),dp(12),dp(10),dp(12));sidebar.setBackgroundColor(railColor);shell.addView(sidebar,new LinearLayout.LayoutParams(dp(76),-1));
        sideNav=column();sideNav.setGravity(Gravity.TOP);ScrollView railScroll=new ScrollView(context);railScroll.setVerticalScrollBarEnabled(false);railScroll.addView(sideNav);sidebar.addView(railScroll,new LinearLayout.LayoutParams(-1,0,1));
        loadSidebar();rebuildSidebar();sidebar.addView(icon("settings","自定义侧栏",v->showSidebarEditor()));
        content=column();shell.addView(content,new LinearLayout.LayoutParams(0,-1,1));
        HorizontalScrollView tabScroll=new HorizontalScrollView(context);tabScroll.setHorizontalScrollBarEnabled(false);tabScroll.setBackgroundColor(railColor);tabsRow=row();tabScroll.addView(tabsRow);tabStrip=tabScroll;content.addView(tabScroll,new LinearLayout.LayoutParams(-1,dp(44)));activeTab=new BrowserTab(pendingUrl);tabs.add(activeTab);rebuildTabs();
        header=row();header.setPadding(dp(8),dp(4),dp(8),dp(4));header.setBackgroundColor(railColor);content.addView(header,new LinearLayout.LayoutParams(-1,dp(60)));
        header.addView(icon("back","后退",v->webBack()));header.addView(icon("forward","前进",v->forward()));header.addView(icon("refresh","刷新",v->reload()));header.addView(icon("home","主页",v->load(Navigation.HOME)));
        address=new EditText(context);address.setSingleLine(true);address.setTextSize(14);address.setTextColor(text);address.setHintTextColor(muted);address.setHint("搜索或输入网址");address.setSelectAllOnFocus(true);address.setBackground(round(field,18));address.setPadding(dp(16),0,dp(12),0);address.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);address.setImeOptions(EditorInfo.IME_ACTION_GO);address.setOnEditorActionListener((v,a,e)->{navigate();return true;});header.addView(address,new LinearLayout.LayoutParams(0,dp(42),1));
        header.addView(icon("search","打开网址 / 搜索",v->navigate()));header.addView(icon("bookmark","收藏当前页",v->{record("bookmarks");notice("已收藏");}));header.addView(icon(immersive?"exit":"curve",immersive?"退出沉浸模式":"进入沉浸模式",v->{if(immersive)host.exit();else host.mode("cinema");}));header.addView(icon("settings","菜单",v->showSettings()));
        compact=row();compact.setPadding(dp(8),0,dp(8),0);compact.setBackgroundColor(railColor);compact.addView(icon("back","网页后退",v->webBack()));compact.addView(icon("forward","网页前进",v->forward()));compact.addView(icon("volume","播放与音量",v->showPlayerControls()));compact.addView(new View(context),new LinearLayout.LayoutParams(0,1,1));compact.addView(icon("fullscreen","退出全屏",v->leaveFocus()));content.addView(compact,new LinearLayout.LayoutParams(-1,dp(56)));compact.setVisibility(GONE);
        progress=new ProgressBar(context);progress.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(muted));FrameLayout.LayoutParams progressPosition=new FrameLayout.LayoutParams(dp(16),dp(16),Gravity.BOTTOM|Gravity.LEFT);progressPosition.leftMargin=dp(84);progressPosition.bottomMargin=dp(24);addView(progress,progressPosition);progress.setVisibility(GONE);
        stage=new FrameLayout(context);stage.setBackgroundColor(bg);content.addView(stage,new LinearLayout.LayoutParams(-1,0,1));status=label("",12,muted);status.setPadding(dp(12),dp(8),dp(12),dp(8));status.setMaxLines(2);status.setEllipsize(android.text.TextUtils.TruncateAt.END);status.setBackground(round(railColor,8));status.setVisibility(GONE);FrameLayout.LayoutParams statusPosition=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.LEFT);statusPosition.leftMargin=dp(106);statusPosition.bottomMargin=dp(12);statusPosition.rightMargin=dp(18);addView(status,statusPosition);
        loading=column();loading.setGravity(Gravity.BOTTOM|Gravity.LEFT);loading.setPadding(dp(16),dp(16),dp(16),dp(20));loading.setBackgroundColor(bg);stage.addView(loading,new FrameLayout.LayoutParams(-1,-1));loading.setVisibility(GONE);
        tooltip=label("",14,Color.WHITE);tooltip.setPadding(dp(13),dp(9),dp(13),dp(9));tooltip.setBackground(round(0xEE24262D,8));tooltip.setElevation(dp(20));tooltip.setVisibility(GONE);tooltip.setClickable(false);addView(tooltip,new FrameLayout.LayoutParams(-2,-2));if(!immersive)post(this::startBrowsing);if(immersive)post(playerPoll);
    }

    private void forgetIcons(View root){icons.removeIf(i->{ViewParent parent=i.getParent();while(parent instanceof View){if(parent==root)return true;parent=parent.getParent();}return false;});}
    private JSONObject sidebarItem(String name,String glyph,String action,String url){JSONObject o=new JSONObject();try{o.put("name",name).put("icon",glyph).put("action",action).put("url",url).put("enabled",true);}catch(JSONException ignored){}return o;}
    private void defaultSidebar(){sidebarItems.clear();sidebarItems.add(sidebarItem("主页","home","link",Navigation.HOME));sidebarItems.add(sidebarItem("热门","fire","link","https://www.bilibili.com/v/popular/all/"));sidebarItems.add(sidebarItem("动态","feed","link","https://t.bilibili.com/"));sidebarItems.add(sidebarItem("历史","history","history",""));sidebarItems.add(sidebarItem("收藏","bookmark","bookmarks",""));sidebarItems.add(sidebarItem("影院调节","curve","cinema",""));sidebarItems.add(sidebarItem("明暗主题","theme","theme",""));sidebarItems.add(sidebarItem("退出","exit","exit",""));}
    private void loadSidebar(){try{String saved=prefs.getString("sidebarButtons",null);if(saved==null){defaultSidebar();return;}JSONArray a=new JSONArray(saved);for(int i=0;i<a.length();i++)sidebarItems.add(a.getJSONObject(i));}catch(JSONException e){defaultSidebar();}}
    private void saveSidebar(){prefs.edit().putString("sidebarButtons",new JSONArray(sidebarItems).toString()).apply();rebuildSidebar();}
    private void rebuildSidebar(){forgetIcons(sideNav);sideNav.removeAllViews();for(JSONObject o:sidebarItems)if(o.optBoolean("enabled",true))sideNav.addView(icon(o.optString("icon","bookmark"),o.optString("name","快捷入口"),v->{switch(o.optString("action","link")){case "history":showLibrary("历史","history");break;case "bookmarks":showLibrary("收藏","bookmarks");break;case "cinema":openCinema();break;case "theme":toggleTheme();break;case "exit":host.exit();break;default:load(o.optString("url",Navigation.HOME));}}));}
    private void showSidebarEditor(){LinearLayout p=sheet("自定义侧栏");for(int i=0;i<sidebarItems.size();i++){final int index=i;JSONObject o=sidebarItems.get(i);LinearLayout r=row();CheckBox enabled=new CheckBox(getContext());enabled.setText(o.optString("name"));enabled.setTextColor(text);enabled.setChecked(o.optBoolean("enabled",true));enabled.setOnCheckedChangeListener((b,value)->{try{o.put("enabled",value);}catch(JSONException ignored){}saveSidebar();});r.addView(enabled,new LinearLayout.LayoutParams(0,dp(58),1));r.addView(icon("up","上移",v->{if(index>0){Collections.swap(sidebarItems,index,index-1);saveSidebar();showSidebarEditor();}}));r.addView(icon("down","下移",v->{if(index+1<sidebarItems.size()){Collections.swap(sidebarItems,index,index+1);saveSidebar();showSidebarEditor();}}));r.addView(icon("settings","编辑名称、图标和链接",v->editSidebar(o)));r.addView(icon("clear","移除此按钮",v->{sidebarItems.remove(o);saveSidebar();showSidebarEditor();}));p.addView(r);}LinearLayout actions=row();actions.addView(icon("plus","添加快捷链接",v->editSidebar(null)));actions.addView(icon("reset","恢复默认侧栏",v->{defaultSidebar();saveSidebar();showSidebarEditor();}));p.addView(actions);}
    private EditText editorField(String value,String hint){EditText e=new EditText(getContext());e.setText(value);e.setHint(hint);e.setTextColor(text);e.setHintTextColor(muted);e.setSingleLine();return e;}
    private void editSidebar(JSONObject item){LinearLayout p=sheet(item==null?"添加快捷链接":"编辑侧栏按钮");EditText name=editorField(item==null?"":item.optString("name"),"悬停显示的名称");p.addView(name);String action=item==null?"link":item.optString("action","link");EditText link=editorField(item==null?"https://":item.optString("url"),"HTTPS 网址");if("link".equals(action))p.addView(link);String[] glyphs={"home","bookmark","search","fire","feed","live","tv","film","user","history","curve","theme","settings","play","exit"};String[] glyphNames={"主页","收藏","搜索","热门","动态","直播","电视","电影","用户","历史","曲面影院","明暗主题","设置","播放","退出"};Spinner spinner=new Spinner(getContext());ArrayAdapter<String> adapter=new ArrayAdapter<>(getContext(),android.R.layout.simple_spinner_dropdown_item,glyphNames);spinner.setAdapter(adapter);for(int i=0;i<glyphs.length;i++)if(glyphs[i].equals(item==null?"bookmark":item.optString("icon")))spinner.setSelection(i);p.addView(spinner);Button save=new Button(getContext());save.setText("保存");save.setOnClickListener(v->{String n=name.getText().toString().trim(),u=link.getText().toString().trim();if(n.isEmpty()){notice("请填写名称");return;}if("link".equals(action)&&!Navigation.isWeb(u)){notice("请填写完整 HTTPS 网址");return;}JSONObject o=item==null?sidebarItem(n,glyphs[spinner.getSelectedItemPosition()],action,u):item;try{o.put("name",n).put("icon",glyphs[spinner.getSelectedItemPosition()]).put("url",u);}catch(JSONException ignored){}if(item==null)sidebarItems.add(o);saveSidebar();showSidebarEditor();});p.addView(save);}
    private void rebuildTabs(){forgetIcons(tabsRow);tabsRow.removeAllViews();tabStrip.setBackgroundColor(railColor);for(BrowserTab t:tabs){LinearLayout r=row();r.setBackground(round(t==activeTab?field:railColor,10));TextView title=label(t.title,13,text);title.setPadding(dp(12),0,dp(6),0);title.setSingleLine();title.setEllipsize(android.text.TextUtils.TruncateAt.END);title.setOnClickListener(v->activateTab(t));r.addView(title,new LinearLayout.LayoutParams(dp(160),dp(40)));CinemaIcon close=icon("close","关闭标签页",v->closeTab(t));close.setLayoutParams(new LinearLayout.LayoutParams(dp(36),dp(40)));r.addView(close);tabsRow.addView(r);}CinemaIcon add=icon("plus","新建标签页",v->newTab(Navigation.HOME));add.setLayoutParams(new LinearLayout.LayoutParams(dp(44),dp(40)));tabsRow.addView(add);}
    private void activateTab(BrowserTab t){if(t==activeTab)return;closeOverlay();leaveFocus();removeCallbacks(loadTimeout);if(web!=null){web.evaluateJavascript("document.querySelectorAll('video,audio').forEach(v=>v.pause())",null);web.onPause();web.setVisibility(GONE);}activeTab=t;pendingUrl=t.url;web=t.view;pageGeneration++;pageError=false;pagePublished=web!=null;starting=web!=null;loading.setVisibility(GONE);progress.setVisibility(GONE);address.setText(pendingUrl);if(web==null)startBrowsing();else{web.setVisibility(VISIBLE);if(!paused)web.onResume();web.getSettings().setAlgorithmicDarkeningAllowed(dark&&!Navigation.isBili(pendingUrl));adaptPage();if(web.getProgress()<100)beginPage();}rebuildTabs();}
    private void newTab(String url){if(tabs.size()>=6){notice("最多同时打开 6 个标签页");return;}BrowserTab t=new BrowserTab(url);tabs.add(t);activateTab(t);}
    private void closeTab(BrowserTab t){if(t==activeTab){if(tabs.size()==1)tabs.add(new BrowserTab(Navigation.HOME));int index=tabs.indexOf(t);activateTab(tabs.get(index==0?1:index-1));}tabs.remove(t);if(t.view!=null){stage.removeView(t.view);t.view.stopLoading();t.view.destroy();t.view=null;}rebuildTabs();}

    private void palette(){bg=dark?0xFF000000:0xFFFFFFFF;railColor=dark?0xFF14151B:0xFFF7F8FA;text=dark?0xFFE7E8ED:0xFF252A34;muted=dark?0xFF9CA0AC:0xFF8A909C;field=dark?0xFF292B34:0xFFF1F2F4;}
    private LinearLayout row(){LinearLayout v=new LinearLayout(getContext());v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private LinearLayout column(){LinearLayout v=row();v.setOrientation(LinearLayout.VERTICAL);return v;}
    private void space(LinearLayout v,int size){v.addView(new View(getContext()),new LinearLayout.LayoutParams(dp(size),dp(size)));}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private TextView label(String s,int size,int color){TextView v=new TextView(getContext());v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private CinemaIcon icon(String name,String hint,OnClickListener action){CinemaIcon v=new CinemaIcon(getContext(),name,hint,dark,this,action);v.setLayoutParams(new LinearLayout.LayoutParams(dp(52),dp(52)));icons.add(v);return v;}
    @Override public void showHint(View anchor,String hint){if(disposed||!anchor.isShown())return;if(tooltip.getVisibility()==VISIBLE&&hint.contentEquals(tooltip.getText()))return;tooltip.setText(hint);FrameLayout.LayoutParams position=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.LEFT);position.leftMargin=dp(focus?34:106);position.bottomMargin=dp(12);position.rightMargin=dp(18);tooltip.setLayoutParams(position);status.setAlpha(0f);progress.setAlpha(0f);tooltip.setVisibility(VISIBLE);tooltip.bringToFront();}
    @Override public void hideHint(){tooltip.setVisibility(GONE);status.setAlpha(1f);progress.setAlpha(1f);}
    private void loadingSlow(){if(!disposed&&web!=null&&!pagePublished){progress.setVisibility(GONE);notice("网页加载较慢，可刷新重试。",true);}}
    private void beginPage(){videoPlaying=false;host.cursorVisible(true);pageGeneration++;pageFinished=false;pagePublished=false;pageError=false;loading.setVisibility(GONE);if(web!=null){web.setAlpha(1f);web.setEnabled(true);}progress.setVisibility(VISIBLE);removeCallbacks(loadTimeout);postDelayed(loadTimeout,20000);}
    private void publishPage(int generation){if(disposed||web==null||generation!=pageGeneration||pageError)return;pagePublished=true;removeCallbacks(loadTimeout);loading.setVisibility(GONE);web.setAlpha(1f);web.setEnabled(true);progress.setVisibility(GONE);notice("");record("history");CookieManager.getInstance().flush();activeTab.url=url();activeTab.title=web.getTitle()==null?"网页":web.getTitle();rebuildTabs();if(!address.hasFocus())address.setText(url());Log.i("CinemaBrowser","BROWSER_PAGE_VISIBLE");if(diagnostic)postDelayed(this::snapshot,900);}
    private void monitorPage(){}
    /** Keep the native panel's first frame independent of WebView initialization. */
    public void startBrowsing(){if(disposed||starting)return;starting=true;Log.i("CinemaBrowser","WEB_CREATE_BEGIN immersive="+immersive);try{
        web=new WebView(getContext());web.setBackgroundColor(bg);activeTab.view=web;final WebView owner=web;stage.addView(web,0,new FrameLayout.LayoutParams(-1,-1));mobileAgent=web.getSettings().getUserAgentString();configure(web);setAgent();
        web.setWebViewClient(new WebViewClient(){
            @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return r.isForMainFrame()&&block(r.getUrl().toString());}
            @Override public void onPageStarted(WebView v,String url,Bitmap b){if(v!=web)return;pendingUrl=url;activeTab.url=url;beginPage();if(!address.hasFocus())address.setText(url);}
            @Override public void onPageCommitVisible(WebView v,String url){if(disposed||v!=web||pageError)return;adaptPage();loading.setVisibility(GONE);web.setAlpha(1f);web.setEnabled(true);}
            @Override public void onPageFinished(WebView v,String url){if(disposed||v!=web||pageError)return;pendingUrl=url;pageFinished=true;adaptPage();publishPage(pageGeneration);Log.i("CinemaBrowser","WEB_PAGE_FINISHED host="+Uri.parse(url).getHost());}
            @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String purpose="";for(Map.Entry<String,String> h:r.getRequestHeaders().entrySet())if(h.getKey().equalsIgnoreCase("Purpose")||h.getKey().equalsIgnoreCase("Sec-Purpose"))purpose+=h.getValue();if(purpose.toLowerCase(Locale.ROOT).contains("prefetch"))return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));return null;}
            @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(v==web&&r.isForMainFrame()){pageError=true;pageFinished=false;removeCallbacks(pageMonitor);removeCallbacks(loadTimeout);progress.setVisibility(GONE);notice("网页加载失败："+e.getDescription(),true);loading.setVisibility(GONE);}}
            @Override public void onReceivedSslError(WebView v,SslErrorHandler h,SslError e){h.cancel();if(v!=web)return;pageError=true;pageFinished=false;removeCallbacks(pageMonitor);removeCallbacks(loadTimeout);progress.setVisibility(GONE);notice("证书校验失败，请检查网络和时间。",true);loading.setVisibility(GONE);}
        });
        web.setWebChromeClient(new WebChromeClient(){
            @Override public void onReceivedTitle(WebView v,String title){for(BrowserTab t:tabs)if(t.view==v){t.title=title==null?"网页":title;t.url=v.getUrl()==null?t.url:v.getUrl();break;}rebuildTabs();}
            @Override public void onProgressChanged(WebView v,int value){if(v!=web)return;progress.setVisibility(pagePublished||pageError?GONE:VISIBLE);}
            @Override public void onShowCustomView(View v,CustomViewCallback callback){if(owner!=web||fullscreenView!=null){callback.onCustomViewHidden();return;}hideHint();closeOverlay();fullscreenView=v;fullscreenCallback=callback;web.setVisibility(GONE);stage.addView(v,new FrameLayout.LayoutParams(-1,-1));focus=true;updateChrome();Log.i("CinemaBrowser","VIDEO_FULLSCREEN_ENTER");}
            @Override public void onHideCustomView(){leaveFocus();}
            @Override public boolean onCreateWindow(WebView v,boolean dialog,boolean gesture,Message msg){if(!gesture||v!=web)return false;WebView popup=new WebView(getContext());popups.add(popup);popup.setWebViewClient(new WebViewClient(){private void route(String url){if("about:blank".equals(url))return;if(!block(url))load(url);popup.post(()->releasePopup(popup));}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){route(r.getUrl().toString());return true;}@Override public void onPageStarted(WebView v,String url,Bitmap b){popup.stopLoading();route(url);}});((WebView.WebViewTransport)msg.obj).setWebView(popup);msg.sendToTarget();popup.postDelayed(()->releasePopup(popup),15000);return true;}
        });web.setDownloadListener((u,a,d,m,l)->notice("当前版本暂不支持文件下载。"));web.loadUrl(pendingUrl);if(paused)web.onPause();Log.i("CinemaBrowser","WEB_CREATE_COMPLETE");
    }catch(RuntimeException e){Log.e("CinemaBrowser","WEB_CREATE_FAILED",e);progress.setVisibility(GONE);notice("网页组件启动失败，可用顶栏刷新重试。",true);starting=false;if(web!=null){stage.removeView(web);web.destroy();activeTab.view=null;web=null;}}}
    private void configure(WebView v){WebSettings s=v.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setUseWideViewPort(true);s.setLoadWithOverviewMode(true);s.setSupportMultipleWindows(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSafeBrowsingEnabled(true);s.setAlgorithmicDarkeningAllowed(dark&&!Navigation.isBili(pendingUrl));CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(v,true);}
    private void setAgent(){String agent=mobileAgent;if(prefs.getBoolean("desktop",true)){Matcher m=Pattern.compile("Chrome/([0-9.]+)").matcher(agent);agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/"+(m.find()?m.group(1):"120.0.0.0")+" Safari/537.36";}web.getSettings().setUserAgentString(agent);}
    private void adaptPage(){if(web==null)return;web.getSettings().setAlgorithmicDarkeningAllowed(dark&&!Navigation.isBili(url()));try{if(layoutScript==null){try(InputStream in=getContext().getAssets().open("client-layout.js")){layoutScript=new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);}}web.evaluateJavascript(layoutScript.replace("DARK",dark?"true":"false"),null);}catch(IOException e){notice("布局资源读取失败，请重新安装应用。");}}
    private void toggleTheme(){dark=!dark;prefs.edit().putBoolean("dark",dark).apply();palette();setBackgroundColor(bg);sidebar.setBackgroundColor(railColor);header.setBackgroundColor(railColor);compact.setBackgroundColor(railColor);stage.setBackgroundColor(bg);loading.setBackgroundColor(bg);address.setTextColor(text);address.setHintTextColor(muted);address.setBackground(round(field,18));rebuildTabs();status.setTextColor(muted);status.setBackground(round(railColor,8));progress.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(muted));for(CinemaIcon i:icons)i.dark(dark);for(BrowserTab t:tabs)if(t.view!=null){t.view.setBackgroundColor(bg);t.view.getSettings().setAlgorithmicDarkeningAllowed(dark&&!Navigation.isBili(t.url));}if(web!=null)adaptPage();if(overlay!=null)showSettings();}
    private void navigate(){try{load(Navigation.resolve(address.getText().toString()));address.clearFocus();((InputMethodManager)getContext().getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(address.getWindowToken(),0);}catch(IllegalArgumentException e){notice(e.getMessage());}}
    private boolean block(String url){if(Navigation.isWeb(url))return false;notice("请输入有效的 HTTPS 网址。");return true;}
    public String url(){String u=web==null?pendingUrl:web.getUrl();return Navigation.isWeb(u)?u:pendingUrl;}
    public void load(String url){if(disposed||!Navigation.isWeb(url))return;pendingUrl=url;hideHint();closeOverlay();leaveFocus();beginPage();if(web!=null)web.loadUrl(url);else startBrowsing();}
    private void reload(){if(web==null){startBrowsing();return;}leaveFocus();beginPage();web.reload();}
    public void notice(String s){notice(s,false);}
    private void notice(String s,boolean persistent){String message=s==null?"":s.trim();if(message.isEmpty()){removeCallbacks(hideNotice);status.setVisibility(GONE);return;}long now=android.os.SystemClock.uptimeMillis();if(message.equals(lastNotice)&&now-lastNoticeAt<12000)return;lastNotice=message;lastNoticeAt=now;removeCallbacks(hideNotice);status.setText(message);status.setVisibility(VISIBLE);status.bringToFront();if(!persistent)postDelayed(hideNotice,3500);}
    public void modeLabel(String s){modeText=s;if(geometryLabel!=null)geometryLabel.setText(s);if(curvatureControl!=null)curvatureControl.setProgress(host.curvature());if(curveValue!=null)curveValue.setText(curvatureText(host.curvature()));}
    public void enterFocus(){if(web==null)return;closeOverlay();hideHint();focus=true;updateChrome();web.evaluateJavascript("(function(){var v=document.querySelector('video');if(!v)return;function expand(){if(window.__questCinemaFocus)return;var n=v.closest('.bpx-player-container')||v.parentElement;window.__questCinemaFocus={node:n,style:n.style.cssText,overflow:document.body.style.overflow};n.style.cssText+=';position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483646!important;background:black!important;';document.body.style.overflow='hidden';}if(document.fullscreenElement)return;try{var p=v.requestFullscreen();if(p&&p.catch)p.catch(expand)}catch(e){expand()}})()",null);}
    public void leaveFocus(){if(web!=null&&!disposed)web.evaluateJavascript("(function(){var f=window.__questCinemaFocus;if(f){f.node.style.cssText=f.style;document.body.style.overflow=f.overflow;delete window.__questCinemaFocus}})()",null);if(fullscreenView!=null){stage.removeView(fullscreenView);fullscreenView=null;if(web!=null)web.setVisibility(VISIBLE);WebChromeClient.CustomViewCallback cb=fullscreenCallback;fullscreenCallback=null;if(cb!=null)cb.onCustomViewHidden();}focus=false;updateChrome();}
    private void updateChrome(){sidebar.setVisibility(focus?GONE:VISIBLE);header.setVisibility(focus?GONE:VISIBLE);tabStrip.setVisibility(focus?GONE:VISIBLE);compact.setVisibility(focus?VISIBLE:GONE);FrameLayout.LayoutParams position=(FrameLayout.LayoutParams)status.getLayoutParams();position.leftMargin=dp(focus?34:106);status.setLayoutParams(position);FrameLayout.LayoutParams indicator=(FrameLayout.LayoutParams)progress.getLayoutParams();indicator.leftMargin=dp(focus?12:84);progress.setLayoutParams(indicator);}
    public boolean back(){if(overlay!=null){closeOverlay();return true;}if(focus){leaveFocus();return true;}if(web!=null&&web.canGoBack()){web.goBack();return true;}return false;}
    private void webBack(){if(web!=null&&web.canGoBack()){closeOverlay();leaveFocus();beginPage();web.goBack();}}
    private void forward(){if(web!=null&&web.canGoForward()){closeOverlay();leaveFocus();beginPage();web.goForward();}}
    private void showSearch(){closeOverlay();leaveFocus();address.requestFocus();((InputMethodManager)getContext().getSystemService(Context.INPUT_METHOD_SERVICE)).showSoftInput(address,InputMethodManager.SHOW_IMPLICIT);}
    private void showChannels(){LinearLayout p=sheet("分类");channel(p,"直播","live","https://live.bilibili.com/");channel(p,"追番","tv","https://www.bilibili.com/anime/");channel(p,"影视","film","https://www.bilibili.com/movie/");}
    private void channel(LinearLayout p,String name,String glyph,String url){LinearLayout r=row();r.addView(icon(glyph,name,v->load(url)));r.addView(label(name,17,text));p.addView(r);}
    private void record(String key){if(web==null)return;String u=url();if(!Navigation.isWeb(u))return;try{JSONArray old=new JSONArray(prefs.getString(key,"[]")),next=new JSONArray();JSONObject item=new JSONObject();item.put("url",u);item.put("title",web.getTitle()==null?u:web.getTitle());next.put(item);for(int i=0;i<old.length()&&next.length()<50;i++){JSONObject o=old.getJSONObject(i);if(!u.equals(o.optString("url")))next.put(o);}prefs.edit().putString(key,next.toString()).apply();}catch(JSONException ignored){}}
    private LinearLayout sheet(String title){hideHint();closeOverlay();ScrollView scroll=new ScrollView(getContext());scroll.setFillViewport(true);scroll.setBackgroundColor(bg);LinearLayout p=column();p.setGravity(Gravity.TOP);p.setPadding(dp(32),dp(20),dp(32),dp(24));scroll.addView(p);LinearLayout top=row();top.addView(label(title,23,text),new LinearLayout.LayoutParams(0,dp(64),1));top.addView(icon("close","关闭",v->closeOverlay()));p.addView(top);overlay=scroll;stage.addView(scroll,new FrameLayout.LayoutParams(-1,-1));return p;}
    private void closeOverlay(){geometryLabel=null;curvatureControl=null;curveValue=null;if(overlay!=null){final View old=overlay;icons.removeIf(i->{ViewParent p=i.getParent();while(p instanceof View){if(p==old)return true;p=p.getParent();}return false;});stage.removeView(overlay);overlay=null;}}
    private void showLibrary(String title,String key){LinearLayout p=sheet(title);if("bookmarks".equals(key))p.addView(icon("bookmark","收藏当前页",v->{record("bookmarks");showLibrary(title,key);}));try{JSONArray a=new JSONArray(prefs.getString(key,"[]"));if(a.length()==0)p.addView(label("还没有记录。",16,muted));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);String u=o.getString("url");LinearLayout r=row();TextView t=label(o.optString("title",u),16,text);t.setSingleLine();t.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(t,new LinearLayout.LayoutParams(0,dp(64),1));r.addView(icon("play","打开视频",v->load(u)));p.addView(r);}p.addView(icon("clear","清空"+title,v->{prefs.edit().remove(key).apply();showLibrary(title,key);}));}catch(JSONException ignored){}}
    private void openCinema(){if(immersive)openCinemaSettings();else host.mode("cinema");}
    private String curvatureText(int value){return value==0?"0% · 平面":value+"% · "+Math.round(value*1.2f)+"°";}
    public void openCinemaSettings(){LinearLayout p=sheet("影院调节");geometryLabel=label(modeText,13,muted);p.addView(geometryLabel);LinearLayout title=row();title.addView(label("曲率",17,text),new LinearLayout.LayoutParams(0,dp(56),1));curveValue=label(curvatureText(host.curvature()),15,muted);title.addView(curveValue);p.addView(title);curvatureControl=new SeekBar(getContext());curvatureControl.setMax(100);curvatureControl.setProgress(host.curvature());curvatureControl.setContentDescription("屏幕曲率，0 为平面，100 为最大曲率");curvatureControl.setProgressTintList(android.content.res.ColorStateList.valueOf(pink));curvatureControl.setThumbTintList(android.content.res.ColorStateList.valueOf(pink));p.addView(curvatureControl,new LinearLayout.LayoutParams(-1,dp(56)));final int[] pending={host.curvature()};final boolean[] queued={false};Runnable apply=()->{queued[0]=false;if(!disposed)host.curvature(pending[0]);};curvatureControl.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar bar,int value,boolean user){if(curveValue!=null)curveValue.setText(curvatureText(value));if(user){pending[0]=value;if(!queued[0]){queued[0]=true;postDelayed(apply,60);}}}public void onStartTrackingTouch(SeekBar bar){}public void onStopTrackingTouch(SeekBar bar){removeCallbacks(apply);pending[0]=bar.getProgress();apply.run();}});p.addView(label("0% 平面 · 25% 轻弯 · 75% 标准 · 100% 最大",13,muted));if(immersive){settingRow(p,"屏幕大小","缩小","grow-","放大","grow+");settingRow(p,"观看距离","靠近","near","远离","far");settingRow(p,"屏幕高度","降低","down","抬高","up");p.addView(icon("reset","重置屏幕并居中",v->host.adjust("reset")));}else p.addView(icon("curve","使用此曲率进入影院",v->host.mode("cinema")));}
    private void showPlayerControls(){LinearLayout p=sheet("播放与音量");p.addView(icon("play","播放 / 暂停",v->{if(web!=null)web.evaluateJavascript("(function(){var v=document.querySelector('.bpx-player-container video,#bilibili-player video,video');if(v){if(v.paused)v.play().catch(()=>{});else v.pause();}})()",null);}));TextView value=label("音量",16,text);p.addView(value);SeekBar bar=new SeekBar(getContext());bar.setMax(100);bar.setContentDescription("视频音量，0 为静音");bar.setProgress(50);p.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));if(web!=null)web.evaluateJavascript("(function(){var v=document.querySelector('.bpx-player-container video,#bilibili-player video,video');return v?(v.muted?0:Math.round(v.volume*100)):50})()",v->{try{if(overlay!=null)bar.setProgress(Integer.parseInt(v));}catch(Exception ignored){}});bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int n,boolean user){value.setText("音量 "+n+"%");if(user&&web!=null)web.evaluateJavascript("window.__questBrowser&&window.__questBrowser.volume("+(n/100f)+")",null);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});}
    private void showSettings(){LinearLayout p=sheet("设置");LinearLayout modes=row();modes.addView(icon("plus","新建标签页",v->newTab(Navigation.HOME)));modes.addView(icon("feed","自定义侧栏",v->showSidebarEditor()));modes.addView(icon("history","历史",v->showLibrary("历史","history")));modes.addView(icon("bookmark","收藏",v->showLibrary("收藏","bookmarks")));modes.addView(icon("volume","播放与音量",v->showPlayerControls()));modes.addView(icon("curve","影院调节",v->openCinemaSettings()));modes.addView(icon("fullscreen","全屏播放",v->enterFocus()));modes.addView(icon("theme","切换明暗主题",v->toggleTheme()));p.addView(modes);
        settingToggle(p,"桌面版网页",prefs.getBoolean("desktop",true),()->{prefs.edit().putBoolean("desktop",!prefs.getBoolean("desktop",true)).apply();if(web!=null){setAgent();closeOverlay();web.reload();}});
        TextView note=label("图标悬停约半秒显示名称；鼠标、手柄射线、键盘焦点及长按均可查看。\n桌面与影院切换会重新载入当前网页，登录状态共用。\n网页播放器决定播放和清晰度。bili233 0.10.2 · 非官方应用。",14,muted);note.setPadding(0,dp(20),0,dp(16));p.addView(note);
        LinearLayout clear=row();clear.addView(label("登录与网页数据",16,text),new LinearLayout.LayoutParams(0,dp(56),1));clear.addView(icon("clear","清除登录和网页数据",v->{LinearLayout confirm=sheet("清除网页数据？");confirm.addView(label("将退出本应用登录，并清除网页缓存。",16,muted));Button b=new Button(getContext());b.setText("确认清除");b.setOnClickListener(a->{if(web==null)return;web.stopLoading();web.loadUrl("about:blank");CookieManager.getInstance().removeAllCookies(done->{if(disposed)return;CookieManager.getInstance().flush();WebStorage.getInstance().deleteAllData();web.clearCache(true);web.clearHistory();load(Navigation.HOME);});});confirm.addView(b);}));p.addView(clear);
    }
    private void settingToggle(LinearLayout p,String title,boolean checked,Runnable action){LinearLayout r=row();r.addView(label(title,16,text),new LinearLayout.LayoutParams(0,dp(58),1));CinemaIcon toggle=icon("settings",title+(checked?"：已开启，点击关闭":"：已关闭，点击开启"),v->action.run());toggle.selected(checked);r.addView(toggle);p.addView(r);}
    private void settingRow(LinearLayout p,String title,String a,String actionA,String b,String actionB){LinearLayout r=row();r.addView(label(title,16,text),new LinearLayout.LayoutParams(0,dp(60),1));r.addView(icon(actionA.equals("down")?"down":"minus",a,v->host.adjust(actionA)));r.addView(icon(actionB.equals("up")?"up":"plus",b,v->host.adjust(actionB)));p.addView(r);}
    private void releasePopup(WebView v){if(popups.remove(v))v.destroy();}
    public void pause(){paused=true;removeCallbacks(playerPoll);host.cursorVisible(true);pointerVisible=false;pointerPressed=false;invalidate();removeCallbacks(pageMonitor);if(web!=null){web.evaluateJavascript("document.querySelectorAll('video,audio').forEach(function(v){v.pause()})",null);web.onPause();}CookieManager.getInstance().flush();}
    public void resume(){paused=false;if(immersive){removeCallbacks(playerPoll);post(playerPoll);}if(web!=null){web.onResume();if(pageFinished){removeCallbacks(pageMonitor);post(pageMonitor);}}}
    public void dispose(){disposed=true;removeCallbacks(playerPoll);host.cursorVisible(true);removeCallbacks(hideNotice);removeCallbacks(loadTimeout);removeCallbacks(pageMonitor);hideHint();leaveFocus();for(WebView p:popups)p.destroy();popups.clear();for(BrowserTab t:tabs)if(t.view!=null){stage.removeView(t.view);t.view.stopLoading();t.view.destroy();t.view=null;}web=null;tabs.clear();}
    /** Draw on the same compositor layer as the hit surface, including above native fullscreen. */
    private void trackPointer(MotionEvent event){if(!immersive)return;int action=event.getActionMasked();float x=event.getX(),y=event.getY();boolean deliberate=action==MotionEvent.ACTION_DOWN||action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_SCROLL||Math.hypot(x-activityPointerX,y-activityPointerY)>dp(5);if(deliberate){activityPointerX=x;activityPointerY=y;pointerActivity=android.os.SystemClock.uptimeMillis();host.cursorVisible(true);}pointerVisible=action!=MotionEvent.ACTION_HOVER_EXIT&&action!=MotionEvent.ACTION_CANCEL&&(!videoPlaying||pointerPressed||android.os.SystemClock.uptimeMillis()-pointerActivity<2500);pointerX=x;pointerY=y;if(action==MotionEvent.ACTION_DOWN)pointerPressed=true;if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL)pointerPressed=false;invalidate();}
    @Override public boolean dispatchHoverEvent(MotionEvent event){trackPointer(event);return super.dispatchHoverEvent(event);}
    @Override public boolean dispatchGenericMotionEvent(MotionEvent event){if(event.isFromSource(InputDevice.SOURCE_CLASS_POINTER))trackPointer(event);return super.dispatchGenericMotionEvent(event);}
    private boolean consumeRecenterGesture;
    @Override public boolean dispatchKeyEvent(KeyEvent event){if(immersive&&event.getAction()==KeyEvent.ACTION_DOWN&&event.getRepeatCount()==0&&host.recenterIfNeeded())return true;return super.dispatchKeyEvent(event);}
    @Override public boolean dispatchTouchEvent(MotionEvent event){if(immersive&&host.movingWindow()){consumeRecenterGesture=true;return true;}if(immersive&&event.getActionMasked()==MotionEvent.ACTION_DOWN&&host.recenterIfNeeded())consumeRecenterGesture=true;if(consumeRecenterGesture){if(event.getActionMasked()==MotionEvent.ACTION_UP||event.getActionMasked()==MotionEvent.ACTION_CANCEL)consumeRecenterGesture=false;return true;}trackPointer(event);return super.dispatchTouchEvent(event);}
    @Override protected void dispatchDraw(Canvas canvas){super.dispatchDraw(canvas);if(!immersive||!pointerVisible)return;pointerPaint.setStyle(Paint.Style.FILL);pointerPaint.setColor(0xB0000000);canvas.drawCircle(pointerX,pointerY,dp(9),pointerPaint);pointerPaint.setColor(pointerPressed?pink:Color.WHITE);canvas.drawCircle(pointerX,pointerY,dp(pointerPressed?5:4),pointerPaint);pointerPaint.setStyle(Paint.Style.STROKE);pointerPaint.setStrokeWidth(dp(2));pointerPaint.setColor(Color.WHITE);canvas.drawCircle(pointerX,pointerY,dp(8),pointerPaint);}
    public void requestDiagnosticSnapshot(){if(BuildConfig.DEBUG)diagnostic=true;}
    /** ADB-only development actions for regression checks; no JavaScript bridge is exposed. */
    public void diagnosticAction(String action){
        if(!BuildConfig.DEBUG||action==null||disposed)return;
        switch(action){
            case "enter-curved":host.mode("curved");break;
            case "flat":host.mode("flat");break;
            case "curved":host.mode("curved");break;
            case "settings":showSettings();break;
            case "fullscreen":enterFocus();break;
            case "new-tab":newTab(Navigation.HOME);break;
            case "sidebar":showSidebarEditor();break;
            case "first-video":if(web!=null)web.evaluateJavascript("(function(){var a=document.querySelector('a[href*=\"/video/BV\"]');return a?a.href:null})()",value->{try{String url=new JSONArray("["+value+"]").getString(0);if(Navigation.isWeb(url))load(url);}catch(JSONException ignored){}});break;
            case "back":back();break;
            case "exit":host.exit();break;
            case "hover-curve":for(CinemaIcon i:icons){if("影院调节".contentEquals(i.getContentDescription())){long time=android.os.SystemClock.uptimeMillis();MotionEvent event=MotionEvent.obtain(time,time,MotionEvent.ACTION_HOVER_ENTER,20,20,0);event.setSource(InputDevice.SOURCE_MOUSE);i.dispatchGenericMotionEvent(event);event.recycle();break;}}break;
        }
        Log.i("CinemaBrowser","DIAGNOSTIC_ACTION "+action);
        diagnostic=true;postDelayed(this::snapshot,900);
    }

    private void snapshot(){if(!diagnostic||disposed||getWidth()==0||getHeight()==0)return;diagnostic=false;try{Bitmap b=Bitmap.createBitmap(getWidth(),getHeight(),Bitmap.Config.ARGB_8888);draw(new Canvas(b));File file=new File(getContext().getExternalFilesDir(null),immersive?"cinema-ui.png":"desktop-ui.png");try(FileOutputStream out=new FileOutputStream(file)){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();Log.i("CinemaBrowser","DIAGNOSTIC_SNAPSHOT_READY");}catch(Exception e){Log.w("CinemaBrowser","DIAGNOSTIC_SNAPSHOT_FAILED",e);}}
}
